# Generated by Django 4.2.7 on 2024-04-12 13:21

from django.db import migrations, models
import women_empowerment.models


class Migration(migrations.Migration):

    dependencies = [
        ('women_empowerment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='story',
            field=models.TextField(default=women_empowerment.models.Woman.random_story),
        ),
    ]
