# Generated by Django 4.2.7 on 2024-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_empowerment', '0002_woman_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='women_images/'),
        ),
    ]
