# Generated by Django 4.2.7 on 2024-04-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_empowerment', '0003_woman_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woman',
            name='image',
        ),
        migrations.AlterField(
            model_name='woman',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
